collect_user_context_task:
  description: >
    Interagir com o usuário através do chatbot para coletar informações detalhadas sobre sua situação socioeconômica, interesses e objetivos, a fim de gerar uma base vetorial de contexto.
  expected_output: >
    Um arquivo JSON contendo a representação vetorial do contexto do usuário, que será usado pelos agentes para buscar oportunidades personalizadas.

find_job_opportunities_task:
  description: >
    Utilizar o contexto vetorizado do usuário para identificar oportunidades de emprego que correspondam ao seu perfil e interesses.
  expected_output: >
    Uma lista de oportunidades de emprego personalizadas relevantes para o usuário.

find_event_opportunities_task:
  description: >
    Utilizar o contexto do usuário para encontrar eventos que possam contribuir para seu desenvolvimento pessoal e profissional.
  expected_output: >
    Uma lista de eventos relevantes para o usuário.

find_course_opportunities_task:
  description: >
    Buscar cursos que atendam às necessidades e interesses educacionais do usuário, com base em seu contexto.
  expected_output: >
    Uma lista de cursos relevantes para o usuário.

find_professional_development_task:
  description: >
    Identificar oportunidades de desenvolvimento profissional, como programas de mentoria e workshops, que se alinhem com os objetivos do usuário.
  expected_output: >
    Uma lista de oportunidades de desenvolvimento profissional relevantes para o usuário.
